epochs: 50
data_path: ../Data/DicData
output_dir: checkpoint
log_dir: log

print_freq: 10
gen_eval_freq: 10
latent_size: 128
input_channel: 1
image_size: 64
batch_size: 256
beta1: 0.5
feature_maps_g: 64
feature_maps_d: 64
lr: 0.0002
seed: 0
n_noise: 8
l1_weight: 100
